### ISSUE TITLE
Profile Display

### ISSUE THREAD

**Issue by dee-me-tree-or-love** [Volunteero/volunteero-front-end-base#5]
**Story goes**
>As a user I would like to be able to access  
my* profile information in a single page
so that I have a concise and clear overivew
of my details

Trello card: [#91](https://trello.com/c/xPu5meDp/91-display-profile-module-in-the-app-fe)

**TODO:**
- [ ] Create profile display module/component
- [ ] Create `header` component
- [ ] Create `feed` component 
- [ ] Display `username`
- [ ] Display user `f_name` and `l_name` 
- [ ] Display other details like `city/location`, `bio` and all that
- [ ] Display user's upcoming and past events
- [ ] Display user's contributions to campaigns 
- [ ] Dstinguish between current user's and a random profile

**Comment by dee-me-tree-or-love** [comment]
![image](https://user-images.githubusercontent.com/12134172/41624612-93d4d9b2-7416-11e8-8469-6fb46691c399.png)
